# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb0cd83f628639bf1acdc106ceb0c1aca87f5d6252d507fd81d0346512746094879c959e6f9ad6be7775f86660d0287643b1664e3f26a0c095afb066705a53d

test:
  secret_key_base: 468a411dee68a8834253d8c18735d0427e8ba8d67f2316c47ad38b4864a07275d826e3a4fc4258a284872b55a66b4a504022813ffb57737a194fae57abfd44df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
